// <auto-generated />
using Fanex.Bot.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fanex.Bot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20180607072328_AddGitLabInfo")]
    partial class AddGitLabInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fanex.Bot.Models.GitLab.GitLabInfo", b =>
                {
                    b.Property<string>("ConversationId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsActive");

                    b.Property<string>("ProjectUrl");

                    b.HasKey("ConversationId");

                    b.ToTable("GitLabInfo");
                });

            modelBuilder.Entity("Fanex.Bot.Models.Log.LogInfo", b =>
                {
                    b.Property<string>("ConversationId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsActive");

                    b.Property<string>("LogCategories");

                    b.HasKey("ConversationId");

                    b.ToTable("LogInfo");
                });

            modelBuilder.Entity("Fanex.Bot.Models.MessageInfo", b =>
                {
                    b.Property<string>("ConversationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChannelId");

                    b.Property<string>("FromId");

                    b.Property<string>("FromName");

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("ServiceUrl");

                    b.Property<string>("ToId");

                    b.Property<string>("ToName");

                    b.HasKey("ConversationId");

                    b.ToTable("MessageInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
