// <auto-generated />
using System;
using Fanex.Bot.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fanex.Bot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20180625060937_AddLogIgnoreMessage")]
    partial class AddLogIgnoreMessage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fanex.Bot.Models.GitLab.GitLabInfo", b =>
                {
                    b.Property<string>("ConversationId");

                    b.Property<string>("ProjectUrl");

                    b.Property<DateTime>("CreatedTime");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("ModifiedTime");

                    b.HasKey("ConversationId", "ProjectUrl");

                    b.ToTable("GitLabInfo");
                });

            modelBuilder.Entity("Fanex.Bot.Models.Log.LogInfo", b =>
                {
                    b.Property<string>("ConversationId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTime");

                    b.Property<bool>("IsActive");

                    b.Property<string>("LogCategories");

                    b.Property<DateTime>("ModifiedTime");

                    b.HasKey("ConversationId");

                    b.ToTable("LogInfo");
                });

            modelBuilder.Entity("Fanex.Bot.Models.MessageInfo", b =>
                {
                    b.Property<string>("ConversationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChannelId");

                    b.Property<DateTime>("CreatedTime");

                    b.Property<string>("FromId");

                    b.Property<string>("FromName");

                    b.Property<bool>("IsAdmin");

                    b.Property<DateTime>("ModifiedTime");

                    b.Property<string>("ServiceUrl");

                    b.Property<string>("ToId");

                    b.Property<string>("ToName");

                    b.HasKey("ConversationId");

                    b.ToTable("MessageInfo");
                });

            modelBuilder.Entity("Fanex.Bot.Skynex.Models.Log.LogIgnoreMessage", b =>
                {
                    b.Property<string>("Category");

                    b.Property<string>("IgnoreMessage");

                    b.HasKey("Category", "IgnoreMessage");

                    b.ToTable("LogIgnoreMessage");
                });
#pragma warning restore 612, 618
        }
    }
}
